title: OACD Group at UCL
menu_title: OACD @ UCL
author: Dept. of Geography, University College London
description:
  The MOAP CMIP6 Hackathon is a 3-day hackathon event, organised by the
  University of Bristol’s Jean Golding Institute and Cabot Institute. Over the
  course of the event, teams of academic researchers from across the UK will
  work on research questions set by the MOAP partners related to earth-system
  science and CMIP6 data.
url: "https://oacd-ucl.github.io"
github_username: oacd-ucl 
theme: minima
header_pages:
  - projects.md
  - about.md
  - resources.md
  - teaching.md
  - other.md

# Remove ".html" from default permalinks
permalink: pretty

# (See default layout below)
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Social media links
# (See default layout below)
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: /assets/advert.png
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Simplify tables of contents
kramdown:
  toc_levels: "2,3"
