title: Ocean, Atmosphere & Climate Dynamics
menu_title: Ocean, Atmosphere and Climate <span class="hide-very-narrow">Dynamics</span><br><small><span class="hide-very-narrow">University</span> College London</small>
author: Dept. of Geography, University College London
description:
  The Ocean, Atmosphere and Climate Dynamics research group at UCL
url: "https://oacd-ucl.github.io"
github_username: oacd-ucl 
theme: minima
header_pages:
  - pages/projects.md
  - pages/about.md
  - pages/resources.md
  - pages/teaching.md
  - pages/other.md

# Remove ".html" from default permalinks
permalink: pretty

# (See default layout below)
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Social media links
# (See default layout below)
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: /assets/advert.png
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Simplify tables of contents
kramdown:
  toc_levels: "2,3"
